### ISSUE TITLE
Choosing images from Camera for training

### ISSUE THREAD

**Issue by manali07** [pillarpond/face-recognizer-android#34]
E/AndroidRuntime: FATAL EXCEPTION: inference
    
    java.lang.IllegalArgumentException: DataType error: cannot resolve DataType of java.nio.ByteBufferAsFloatBuffer
        at org.tensorflow.lite.Tensor.dataTypeOf(Tensor.java:170)
        at org.tensorflow.lite.Tensor.throwExceptionIfTypeIsIncompatible(Tensor.java:230)
        at org.tensorflow.lite.Tensor.copyTo(Tensor.java:116)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:157)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:250)
    ]

**Comment by proxcesumit** [comment]
@pillarpond can you please check? i am facing same error on launch.

**Comment by jay-mao-cn** [comment]
I fixed this issue by updating tensorflow-lite to latest version (2.2.0).
